use_frameworks!

platform :ios, '13.0'

target 'RequestBuilder_Example' do
  pod 'RequestBuilder', :path => '../'

  target 'RequestBuilder_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 6.1.0'
    pod 'Nimble', '~> 11.2.1'
  end
end
